---
#SE OS FOR DEBIAN

#TO-DO 

#valida o diretorio da key e guarda se houver

#copia a key especifica 


#valida o diretorio do cert e guarda se houver

#copia o cert especifica - cert + intermediate

#Levanta os serviços

#WHEN apache restart

#WHEN nginx restart

#- name: "Check se path existe"
#  stat:
#    path: "/etc/certs/{{ item }}/"
#  register: path
#  with_items: "{{ dominios }}"

- name: Verificando se o certificado existe
  stat:
    path: /etc/ssl/certs/{{ item }}.bundle
  loop: "{{ dominios }}"
  register: debian_certs


#- name: copia os certificados 
#  ansible.builtin.copy:
#    src: "files/{{ item.item }}.cert"
#    dest: "/etc/certs/{{ item.item }}/{{ item.item }}.cert"
#    backup: yes
#  notify: restart webserver
#  with_items: "{{ path.results }}"
#  when: item.stat.exists

- name: Instalando certificado
  copy:
    src: "{{ item.item }}.bundle"
    dest: "{{ item.stat.path }}"
    owner: root
    group: root
    mode: '0444'
  when: item.stat.exists
  loop: "{{ debian_certs.results }}"
  notify: restart webserver

- name: Instalando a chave privada (debian way)
  copy:
    src: "{{ item.item }}.key"
    dest: /etc/ssl/private/{{ item.item }}.key
    owner: root
    group: root
    mode: '0400'
  when: item.stat.exists
  loop: "{{ debian_certs.results }}"
  notify: restart webserver
 

  

