---
#SE OS FOR DEBIAN

#TO-DO 

#valida o diretorio da key e guarda se houver

#copia a key especifica 


#valida o diretorio do cert e guarda se houver

#copia o cert especifica - cert + intermediate

#Levanta os serviços

#WHEN apache restart

#WHEN nginx restart

- name: "Check se path existe"
  stat:
    path: "/etc/certs/{{ item }}/"
  register: path
  with_items: "{{ dominios }}"

- name: copia os certificados 
  ansible.builtin.copy:
    src: "files/{{ item.item }}.cert"
    dest: "/etc/certs/{{ item.item }}/{{ item.item }}.cert"
    backup: yes
  notify: restart webserver
  with_items: "{{ path.results }}"
  when: item.stat.exists
