---

- name: Populate service facts
  service_facts:

- name: instala o lsof
  ansible.builtin.package:
    name: lsof
    state: present
    
- name: roda as tarefas referente ao apache
  ansible.builtin.include_tasks:
    file: "{{ ansible_distribution_file_variety }}.yml"

#Se o comando não retorna nada vai falhar o script
- name: Busca o nome do webservice rodando
  shell: "lsof -ni :443 | grep LISTEN | cut -d ' ' -f 1 | tail -n 1"
  register: web_service_name

- name: Ensure webserver is running
  ansible.builtin.service:
    name: "{{ web_service_name }}"
    state: started

