---

#TO-DO 

#valida o diretorio da key e guarda se houver

#copia a key especifica 

#valida o diretorio do cert e guarda se houver

#copia o cert especifica - cert + intermediate
#restarta o httpd


# - name: Ensure apache is running
#   ansible.builtin.service:
#     name: httpd
#     state: started
- name: Verificando se o certificado existe
  stat:
    path: /etc/pki/tls/{{ item }}.bundle
  loop: "{{ dominios }}"
  register: redhat_certs


#- name: copia os certificados 
#  ansible.builtin.copy:
#    src: "files/{{ item.item }}.cert"
#    dest: "/etc/certs/{{ item.item }}/{{ item.item }}.cert"
#    backup: yes
#  notify: restart webserver
#  with_items: "{{ path.results }}"
#  when: item.stat.exists

- name: Instalando certificado
  copy:
    src: "{{ item.item }}.bundle"
    dest: "{{ item.stat.path }}"
    owner: root
    group: root
    mode: '0444'
  when: item.stat.exists
  loop: "{{ redhat_certs.results }}"
  notify: restart webserver

- name: Instalando a chave privada
  copy:
    src: "{{ item.item }}.key"
    dest: /etc/pki/tls/private/{{ item.item }}.key
    owner: root
    group: root
    mode: '0400'
  when: item.stat.exists
  loop: "{{ redhat_certs.results }}"
  notify: restart webserver
